import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Providers from './providers/providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    'shopify-api-key': process.env.NEXT_PUBLIC_SHOPIFY_API_KEY || '',
    // 'shopify-app-origins': process.env.NEXT_PUBLIC_HOST || '',
  },
};

export default async function RootLayout({
  children,
  searchParams,
}: Readonly<{
  children: React.ReactNode;
  searchParams: Promise<{ shop: string; host: string }>;
}>) {
  console.log(searchParams);
  // const { shop, host } = await searchParams;
  // if (!shop || !host) {
  //   return <h1>Missing Shop and Host Parameters</h1>;
  // }

  return (
    <html lang='en'>
      <head>
        {/* We need this always otherwise window.shopify vars wont be availble if we load this later */}
        <link rel='preload' href='https://cdn.shopify.com/shopifycloud/app-bridge.js' as='script' />
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src='https://cdn.shopify.com/shopifycloud/app-bridge.js' />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
